---
# tasks file for ansible-role-node
- name: Add NodeSource package signing key
  apt_key: 
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    state: present

- name: Add NodeSource PPA
  apt_repository: 
    repo: "{{ item }}"
    with_items:
      - deb https://deb.nodesource.com/node_{{ node_major_version }}.x {{ ansible_distribution_release  }} main       
      - deb-src https://deb.nodesource.com/node_{{ node_major_version }}.x {{ ansible_distribution_release  }} main       

- name: Install Node
  apt:
    name: nodejs
    update_cache: yes
    state: present  
